/**
 * Writes config.generated.js from MINISTROS_WS_URL (Vercel env).
 * Example: wss://real-time-live-agent.onrender.com/ws
 */
const fs = require('fs');
const path = require('path');

const fallback = 'wss://real-time-live-agent.onrender.com/ws';
const ws = (process.env.MINISTROS_WS_URL || '').trim() || fallback;
const out = path.join(__dirname, '..', 'config.generated.js');
const body =
  '// Generated by scripts/write-config.js at build time\n' +
  `window.MINISTROS_WS_URL = ${JSON.stringify(ws)};\n`;
fs.writeFileSync(out, body, 'utf8');
console.log(`[ministros] WS URL set for build: ${ws}`);
